# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ec23eb61053def0f4f9711896f92a35a9118588f61508046ac7f9199c82e99d9decc42dd0252b6e53e2ee0e690b4dd1578878654df3a0aeb4a315b970e35b49

test:
  secret_key_base: 5c583c164dce5cce7be709e1947703a8c98f6f39dd5e3569b1d5f7c9c56c26c4224fcf376d18ea9907a1fe1c4c9227b717d99131151e3223330de4b9779d4b59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
